<?php
$notify = false;
$email = "who@example.com";
$mashable_key = '';

$useSlack = 1;
$webhookURL = 'https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/CXXXXXXXXXXXXXXXXXXXXXXX';
$channel = "#instructables";
$botname = 'instructables';
$iconURL = null; #uploaded through webpage for webhook setup.

$dbhost = "db";
$dbport = 3306;
$dbuser = "instructables";
$dbpass = "some_pass";
$dbdatabase = "instructables";
